### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by mengxiangyudlut** [flyywh/J4RNet-Deep-Video-Deraining-CVPR-2018#1]

**Comment by dxli94** [comment]
@mengxiangyudlut 请问是如何解决的？谢谢

**Comment by mengxiangyudlut** [comment]
> @mengxiangyudlut 请问是如何解决的？谢谢

链接: https://pan.baidu.com/s/161oIHk1f9WewDczcGDw8-Q 提取码: any6

**Comment by dxli94** [comment]
> > @mengxiangyudlut 请问是如何解决的？谢谢
> 
> 链接: https://pan.baidu.com/s/161oIHk1f9WewDczcGDw8-Q 提取码: any6

非常感谢！麻烦问一下ground truth是否也可以分享一下，这个链接里只有rain frame。

**Comment by mengxiangyudlut** [comment]
> > > @mengxiangyudlut 请问是如何解决的？谢谢
> > 
> > 
> > 链接: https://pan.baidu.com/s/161oIHk1f9WewDczcGDw8-Q 提取码: any6
> 
> 非常感谢！麻烦问一下ground truth是否也可以分享一下，这个链接里只有rain frame。
有GT，就是那个Processed

**Comment by dxli94** [comment]
> > > > @mengxiangyudlut 请问是如何解决的？谢谢
> > > 
> > > 
> > > 链接: https://pan.baidu.com/s/161oIHk1f9WewDczcGDw8-Q 提取码: any6
> > 
> > 
> > 非常感谢！麻烦问一下ground truth是否也可以分享一下，这个链接里只有rain frame。
> > 有GT，就是那个Processed

明白了，多谢了。
