### ISSUE TITLE
test code detail

### ISSUE THREAD

**Issue by z-xf** [flyywh/J4RNet-Deep-Video-Deraining-CVPR-2018#2]
Hello!
I have some doubts about the test code，
in test_practical.m
51 image = imread([input_dir, '/', num2str(i, '%03d'), '.png'])I
9 frames of the same picture are fed into network in each loop. In this case, the network does not seem to use the information of adjacent frames. Is this a small mistake in writing?

**Comment by flyywh** [comment]
Thank you for your attention! It is a small bug and I have updated the testing code.
